# Generated by Django 4.0.4 on 2022-07-05 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0005_perfil_delete_imagen_alter_avatar_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='avatar',
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
